# .air.toml
[build]
  cmd = "swag init -g cmd/api/main.go -d . --parseDependency --parseInternal -o docs && go build -o ./tmp/main.exe cmd/api/main.go"
  bin = "./tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "docs"]

[misc]
  clean_on_exit = true